server:
  port: 8081
  
spring:
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/favourites
    username: root
    password: favourites
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/bootcamp-realm
